const fs = require('fs');
const yaml = require('js-yaml');
require('dotenv').config();

// 🛡️ IMPORT ONLY WHAT WE ARE USING
const GithubAdapter = require('./adapters/sync/github');
const BasecampAdapter = require('./adapters/sync/basecamp');
const DiscordAdapter = require('./adapters/sync/discord');

// ==========================================
// THE VENDOR-AGNOSTIC ORCHESTRATOR
// ==========================================
async function runGlobalSync() {
    console.log("🌐 Booting T.R.O.N. Universal Sync Engine...");

    try {
        // 1. Fetch all Repositories
        console.log("📥 Fetching GitHub Repositories...");
        const repos = await GithubAdapter.fetchRepos(
            process.env.GITHUB_ORG_NAME, 
            process.env.GITHUB_TOKEN
        );

        // 2. Fetch all PM Boards
        console.log("📥 Fetching Boards from Basecamp...");
        const allBoards = await BasecampAdapter.fetchBoards(
            "6169369",
            "BAhbB0kiAbB7ImNsaWVudF9pZCI6ImUxYzJiNjFkMzFmMThlMzAwZjAyNzk5MTFiNmJhZjk5YjlmODUyMTAiLCJleHBpcmVzX2F0IjoiMjAyNi0wNC0yMFQwNTo1Nzo0N1oiLCJ1c2VyX2lkcyI6WzUzMTc0Mjk5XSwidmVyc2lvbiI6MSwiYXBpX2RlYWRib2x0IjoiNWU2MWUyNGY1OGJlOTQ1MTMwMjQzODZjMTE4MTc4MTAifQY6BkVUSXU6CVRpbWUNhY4fwLmR/eYJOg1uYW5vX251bWkCzAI6DW5hbm9fZGVuaQY6DXN1Ym1pY3JvIgdxYDoJem9uZUkiCFVUQwY7AEY=--d24d99f407803d906b9d3cce8508199080234b4d",
            "obhogate48@gmail.com"
        );
        
        // 3. Fetch all Comm Channels
        console.log("📥 Fetching Channels from Discord...");
        const allChannels = await DiscordAdapter.fetchChannels(
            process.env.DISCORD_BOT_TOKEN
        );

        // Safety check in case APIs returned undefined
        const repoCount = repos ? repos.length : 0;
        const boardCount = allBoards ? allBoards.length : 0;
        const channelCount = allChannels ? allChannels.length : 0;

        console.log(`🧠 Running Matchmaker on ${repoCount} Repos, ${boardCount} Boards, and ${channelCount} Channels...`);
        
        const finalYamlData = {
            _comment: "🤖 Auto-generated by T.R.O.N. Universal Sync Engine",
            projects: []
        };

        // 4. The Universal Flexible Matchmaker
        for (const repo of repos || []) {
            const cleanRepoName = repo.name.toLowerCase().replace(/[^a-z0-9]/g, '');

            const matchedBoard = (allBoards || []).find(b => 
                b.name.toLowerCase().replace(/[^a-z0-9]/g, '') === cleanRepoName
            );

            const matchedChannel = (allChannels || []).find(c => 
                c.name.toLowerCase().replace(/[^a-z0-9]/g, '') === cleanRepoName
            );

            if (matchedBoard || matchedChannel) {
                // 🛡️ THE FIX: Default to basecamp/discord if the adapter forgot to name the tool
                const pmTool = matchedBoard ? (matchedBoard.tool) : "none";
                const commTool = matchedChannel ? (matchedChannel.tool) : "none";
                
                const boardName = matchedBoard ? `[${pmTool}] ${matchedBoard.name}` : "[No PM Tool]";
                const channelName = matchedChannel ? `[${commTool}] #${matchedChannel.name}` : "[No Comm Tool]";
                
                console.log(`✅ MATCH: ${repo.fullName} -> ${boardName} -> ${channelName}`);
                
                finalYamlData.projects.push({
                    repo: repo.fullName,
                    pm_tool: pmTool,
                    board_id: matchedBoard ? matchedBoard.id : null,
                    notification_webhook: matchedChannel ? matchedChannel.webhook : null,
                    // 🛡️ THE FIX: Safely fallback to strings so it never crashes!
                    mapping: matchedBoard ? {
                        todo_column: matchedBoard?.mapping?.todo || "not found_todo_column_id",
                        branch_created: matchedBoard?.mapping?.in_progress || "REPLACE_WITH_IN_PROGRESS_COLUMN_ID",
                        pull_request_opened: matchedBoard?.mapping?.in_review || "REPLACE_WITH_REVIEW_COLUMN_ID",
                        pull_request_closed: matchedBoard?.mapping?.done || "REPLACE_WITH_DONE_COLUMN_ID"
                    } : {}
                });
            }
        }

        // 5. Generate the Master YAML
        console.log(`\n💾 Generating master tron.yaml...`);
        fs.writeFileSync('./tron.yaml', yaml.dump(finalYamlData, { lineWidth: -1 }), 'utf8');
        console.log("🚀 UNIVERSAL SYNC COMPLETE.");

    } catch (error) {
        console.error("❌ Sync Failed:", error);
    }
}

runGlobalSync();